rule step1:
    output:
        "input/mass_spec_results.csv",
        "input/sample_metadata.csv"
    params:
        mass_spec_url="https://storage.yandexcloud.net/students-common/mass_spec_results.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075802Z&X-Amz-Expires=2592000&X-Amz-Signature=8696243c988ba07aaf3b8c3bbf6ef9eedaff7c5d6e4364aea6087493c19e3e39&X-Amz-SignedHeaders=host&response-content-disposition=attachment",
        metadata_url="https://storage.yandexcloud.net/students-common/sample_metadata.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075822Z&X-Amz-Expires=2592000&X-Amz-Signature=10e1273d1fcbd5cba59ca00125eb26a4406c14a0ce39c97bcdd5a266493e8015&X-Amz-SignedHeaders=host&response-content-disposition=attachment"
    container:
        "docker-archive:///home/jupyter-chirkovayd/homeworks/lesson_11/image_step1.tar"
    shell:
        """
        mkdir -p input
        wget -O {output[0]} "{params.mass_spec_url}"
        wget -O {output[1]} "{params.metadata_url}"
        """

rule step2:
    input:
        "input/mass_spec_results.csv",
        "input/sample_metadata.csv",
        "script.R"
    output: directory('output')
    container:
        "docker-archive:///home/jupyter-chirkovayd/homeworks/lesson_11/image_step2.tar"
    shell:
        """
        mkdir -p {output}
        Rscript {input[2]} 
        """
